### ISSUE TITLE
firmware_version appears twice in sensors result

### ISSUE THREAD

**Issue by bergvdm** [meetjestad/website#16]
The "firmware_version" key appears twice in the json data result, which makes it "invalid" json

`{
		"row": 3,
		"id": 475,
		"timestamp": "2021-10-20 12:44:05",
		"firmware_version": 2,
		"longitude": 5.10144,
		"latitude": 51.5817,
		"temperature": 17.375,
		"humidity": 102.812,
		"supply": 3.37,
		"firmware_version": 2
	},`

Although there is some debate about duplicate keys in json, in this case it's seems easy to fix.

**Comment by matthijskooijman** [comment]
This was fixed by #17.
